project:
  type: website
  resources: 
  - assets/*

website:
  title: "Deep 7 Research Track"  
  site-url: "https://moshima-pifsc.github.io/2025-01-ISC-OpenScienceTraining" 
  repo-url: "https://github.com/MOshima-PIFSC/Deep7_website"
  repo-actions: [source, issue]
  search: true
  back-to-top-navigation: true
  bread-crumbs: false
  navbar:
    search: true
    backround: "#A5AAAF"
    tools:
      - icon: github
        href: https://github.com/MOshima-PIFSC/Deep7_website
    left: 
      - text: "Modules"
        file: assets/modules.qmd
      - text: "Meeting Notes"
        href: assets/meeting_notes.html
      - text: "Presentation"
        href: assets/presentation.qmd
      - text: "BFVR Non-Commercial Catch App"
        href: https://connect.fisheries.noaa.gov/content/093fc1b8-928f-4ee0-8c3d-bae82dc78295
      

format: 
  html:
    toc: true
    toc-expand: false
    theme:
      - default
      - assets/customizations/website-custom.scss
